const base = require("./jest.config");

module.exports = {
  ...base,
  roots: ["<rootDir>/src", "<rootDir>/tests/eval"],
  testMatch: [
    "**/src/app.test.ts",
    "**/src/staticPagesRouter.test.ts",
    "**/src/authValidation.test.ts",
    "**/src/todoService.test.ts",
    "**/src/validation.test.ts",
    "**/src/aiContracts.test.ts",
    "**/src/aiService.test.ts",
    "**/src/prismaTodoService.error.test.ts",
    "**/src/api.contract.test.ts",
    "**/src/aiQuotaService.test.ts",
    "**/src/aiApplyService.test.ts",
    "**/src/agentRouter.test.ts",
    "**/src/mcpRouter.test.ts",
    "**/src/mcpPublicRouter.test.ts",
    "**/src/mcpOAuthService.test.ts",
    "**/src/mcpAppRouter.test.ts",
    "**/src/pluginPackage.test.ts",
    "**/src/agentIdempotencyService.test.ts",
    "**/src/ai/recommendationSchema.test.ts",
    "**/tests/eval/recommendation-quality.test.ts",
    "**/src/cli/**/*.test.ts",
    // Adaptation system
    "**/src/services/userAdaptationScoring.test.ts",
    "**/src/services/userAdaptationService.test.ts",
    "**/src/services/surfacePolicy.test.ts",
    "**/src/services/adaptationLlmInference.test.ts",
    "**/src/services/adaptationFlags.test.ts",
    "**/src/services/planningPreferencesService.test.ts",
    "**/src/services/adaptationProjectInferenceService.test.ts",
  ],
};
